name: Deploy to Dev Environment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy-dev" to confirm'
        required: true
        default: 'cancel'

env:
  AWS_REGION: eu-west-1

jobs:
  deploy:
    if: github.event.inputs.confirm == 'deploy-dev'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Generate names
      id: names
      run: |
        UNIQUE_ID=$(echo $GITHUB_SHA | cut -c1-7)
        echo "STACK_NAME=dev-$UNIQUE_ID-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "STACK_NAME_SHORT=dev-$UNIQUE_ID" >> $GITHUB_ENV
        echo "STACK_NAME=${STACK_NAME}" >> $GITHUB_OUTPUT
        echo "STACK_NAME_SHORT=${STACK_NAME_SHORT}" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: SAM deploy
      run: |
        sam deploy \
          --stack-name ${{ env.STACK_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
              "Environment=dev \
              NotificationEmail=${{ secrets.NOTIFICATION_EMAIL }} \
              StackNameShort=${{ env.STACK_NAME_SHORT }}" \
          --no-confirm-changeset \
          --resolve-s3