name: Deploy to Dev Environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  STACK_NAME: s3-sns-notifier-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Install AWS SAM CLI
      run: |
        pip install --user aws-sam-cli
        sam --version
    
    - name: SAM Build
      run: sam build
    
    - name: SAM Deploy
      run: |
        sam deploy \
          --stack-name ${{ env.STACK_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
              Environment=dev \
              NotificationEmail=${{ secrets.NOTIFICATION_EMAIL }}
